# Generated by Django 4.2.3 on 2023-07-07 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BDE_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.IntegerField()),
                ('emp_name', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=256)),
                ('date', models.DateField(blank=True, default='')),
                ('technology', models.CharField(blank=True, max_length=256)),
                ('requirement_recieved', models.BooleanField(default=False)),
                ('resume_shared', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Round3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('screenshot_shared', models.BooleanField(default=False)),
                ('our_review', models.TextField(default='')),
                ('client_review', models.TextField(default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Round2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('screenshot_shared', models.BooleanField(default=False)),
                ('our_review', models.TextField(default='')),
                ('client_review', models.TextField(default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Round1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('screenshot_shared', models.BooleanField(default=False)),
                ('our_review', models.TextField(default='')),
                ('client_review', models.TextField(default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
    ]
