# Generated by Django 4.2.3 on 2023-07-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='requirement_recieved',
            field=models.CharField(default='', max_length=256),
        ),
    ]
