# Generated by Django 4.1.4 on 2023-07-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_requirement_recieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round2',
            name='screenshot_shared',
            field=models.FileField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
