# Generated by Django 4.2.3 on 2023-07-13 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bde_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bde_user'),
        ),
        migrations.AddField(
            model_name='round1',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bde_user'),
        ),
        migrations.AddField(
            model_name='round2',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bde_user'),
        ),
        migrations.AddField(
            model_name='round3',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bde_user'),
        ),
    ]
