# Generated by Django 4.2.3 on 2023-07-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_project_edited_by_round1_edited_by_round2_edited_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round1',
            name='date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='round2',
            name='date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='round3',
            name='date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
