# Generated by Django 4.2.3 on 2023-07-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_round1_date_alter_round2_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round1',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='round2',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='round3',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
