# Generated by Django 4.2.3 on 2023-07-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_round1_date_alter_round2_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='requirement_recieved',
        ),
    ]
