# Generated by Django 4.2.3 on 2023-07-25 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_project_requirement_recieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='job_description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='bde_user',
            name='emp_name',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(code='invalid_emp_name', message='Employee name should contain only letters and spaces.', regex='^[a-zA-Z\\s]+$')]),
        ),
    ]
